name: quark
description: "quark - an audioplayer. quark - where sound begins. made by PDG"
publish_to: 'none'

version: 0.2.3

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  hive: ^2.2.3
  path: ^1.9.1
  logging: ^1.3.0
  animations: ^2.1.1
  url_launcher: ^6.3.2
  audioplayers: ^6.5.1
  file_picker: ^10.3.3
  smtc_windows: ^1.1.0
  yandex_music: ^1.2.2  
  path_provider: ^2.1.5
  audio_service: ^0.18.18
  cupertino_icons: ^1.0.8
  animated_expand: ^1.0.2
  interactive_slider: ^0.5.1
  audio_service_mpris: ^0.2.0
  flutter_inappwebview: ^6.2.0-beta.2
  audio_metadata_reader: ^1.4.2
  material_symbols_icons: ^4.2892.0
  window_manager: ^0.5.1
  provider: ^6.1.5+1
  desktop_multi_window: ^0.3.0
  crypto: ^3.0.7
  # isar: ^3.1.0+1
  animated_digit: ^3.3.2
  animated_text_kit: ^4.3.0
  intl: ^0.20.2
  # isar_flutter_libs: ^3.1.0+1
  google_fonts: ^6.3.2  


dependency_overrides:
  yandex_music:
    path: ./lib/overrided_libraries/yandex_music
  animated_expand:
    path: ./lib/overrided_libraries/animated_expand

linter:
  rules:
    - no_assignments_in_conditions
    - prefer_equal_for_default_values
    - always_put_control_body_on_new_line
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13


flutter:
  uses-material-design: true
  assets:
    - assets/icon512.png
  shaders:
    - shaders/vibe.frag