name: quark
description: "quark - an audioplayer. quark - where sound begins. made by PDG"
publish_to: 'none'

version: 0.2.3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  hive: ^2.2.3
  logging: ^1.3.0
  yandex_music: ^1.2.1
  url_launcher: ^6.3.2
  audioplayers: ^6.5.1
  file_picker: ^10.3.3
  smtc_windows: ^1.1.0
  path_provider: ^2.1.5
  window_manager: ^0.5.1
  audio_service: ^0.18.18
  cupertino_icons: ^1.0.8
  interactive_slider: ^0.5.1
  audio_service_mpris: ^0.2.0
  cached_network_image: ^3.4.1
  flutter_inappwebview: ^6.1.5
  audio_metadata_reader: ^1.4.2
  animated_expand: ^1.0.2
  wheel_slider: ^1.2.2
  animations: ^2.1.1
  
dependency_overrides:
  yandex_music:
    path: ./lib/yandex_music

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon512.png
