name: quark
description: "quarkaudio player. penises development group entertaiment."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.2.0
  hive: ^2.2.3
  interactive_slider: ^0.5.1
  logging: ^1.3.0
  path_provider: ^2.1.5
  http: ^1.4.0
  audioplayers: ^6.5.0
  dio: ^5.9.0
  audio_metadata_reader: ^1.4.2
  smtc_windows: ^1.0.0
  audio_service_mpris: ^0.2.0
  audio_service: ^0.18.18
  flutter_inappwebview: ^6.1.5
  cached_network_image: ^3.4.1
  dbus: ^0.7.11
  yandex_music: ^1.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  yandex_music:
    path: ./lib/src/yandex_music_modified

flutter:
  uses-material-design: true
  assets:
      - assets/play.png
      - assets/icon.png
